[package]
name = "rvsp"
version = "0.1.3"
edition = "2021"
description = "Audio spectrum visualizer in Rust"
authors = ["xsbee <xyesbee@protonmail.com>", "Cynthia <cynthia2048@proton.me>"]
license = "GPL-3.0"
keywords = ["audio", "fft", "sdl2", "visualizer"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realfft = "3.4.0"
sdl2 = "0.37.0"
circular-buffer = "0.1.9"
skia-safe = { version = "0.81.0", features = ["wayland", "gpu"] }
