[package]
name = "rvsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realfft = "3.1.0"
sdl2 = "0.35.2"
const_format = "0.2.30"
clap = { version = "4.0.27", features = ["derive"] }