[package]
name = "rvsp"
version = "0.1.2"
edition = "2021"
description = "Audio spectrum visualizer in Rust"
authors = ["xsbee <xyesbee@protonmail.com>", "Cynthia <cynthia2048@proton.me>"]
license = "GPL-3.0"
keywords = ["audio", "fft", "sdl2", "visualizer"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realfft = "3.4.0"
sdl2 = "0.37.0"
const_format = "0.2.33"
clap = { version = "4.5.20", features = ["derive"] }
