[package]
name = "rvsp"
version = "0.1.4"
edition = "2021"
description = "Audio spectrum visualizer in Rust"
authors = ["Cynthia <cynthia2048@proton.me>"]
license = "GPL-3.0"
keywords = ["audio", "fft", "sdl3", "visualizer"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realfft = "3.4.0"
sdl3 = { version = "0", features = [] }
circular-buffer = "0.1.9"
gl = { git = "https://github.com/bjz/gl-rs" }
lazy_static = "1.5.0"
